#!/bin/bash

##################################################
# SBATCH
##################################################

#SBATCH --chdir ./job/${case_name}
#SBATCH --nodes 1
#SBATCH --ntasks ${job_np}
#SBATCH --ntasks-per-node ${job_np}
#SBATCH --time ${job_time}
#SBATCH --account wire
#SBATCH --partition h100
#SBATCH --gres gpu:${job_np}
#SBATCH --gpus-per-node=${job_np}
###SBATCH --cpus-per-task=1
###SBATCH --gpus-per-task=1

##################################################
# MODULE
##################################################

ulimit -s unlimited
ulimit -c unlimited

##################################################
# JOB
##################################################
# RUN
module purge

export PATH=/work/wire/nvhpc-23.3/comm_libs/mpi/bin:/work/wire/nvhpc-23.3/compilers/bin:$PATH
export LD_LIBRARY_PATH=/work/wire/nvhpc-23.3/math_libs/12.0/lib64:/work/wire/nvhpc-23.3/comm_libs/mpi/lib:/work/wire/nvhpc-23.3/compilers/lib:$LD_LIBRARY_PATH
export OPAL_PREFIX=/work/wire/nvhpc-23.3/comm_libs/mpi/
# export OMPI_MCA_use_eager_rdma=1 
# export OMPI_MCA_mtu=4096 
# export OMPI_MCA_max_inline_data=256
# export OMPI_MCA_btl_smcuda_use_cuda_ipc=1
# export OMPI_MCA_btl_openib_warn_no_device_params_found=0

cp input/config log && cd src && make -j${job_np} && mpirun --bind-to none -np ${job_np} ./wireles_src >> ../log
# cp input/config log && cd src && make -j${job_np} && srun --mpi=pmix ./wireles_src >> ../log
# cp input/config log && cd src && make -j${job_np} && mpirun -np ${job_np} ./wireles_src >> ../log
# cp input/config log && cd src && make -j${job_np} && srun --cpu-bind none ./wireles_src >> ../log
